language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'

sudo: false

env:
    - DB_NAME=raster_test PYTHONPATH=$PYTHONPATH:$PWD DJANGO_SETTINGS_MODULE=tests.testproj.settings

before_script:
  - psql -c 'create database raster_test' -U postgres
  - psql -c 'create extension postgis' -U postgres -d raster_test

install:
  - pip install https://github.com/geodesign/django/archive/geodesign_v7.tar.gz
<<<<<<< bc0b19fa0ab8254335dd4a6ff2a2656b5185c69a
  - pip install -e .
=======
>>>>>>> Added merge migration after rebase from master.
  - pip install psycopg2==2.7.1
  - pip install flake8==3.3.0
  - pip install isort==4.2.2
  - pip install coverage==4.4
  - pip install coveralls

script: coverage run --include="raster/*" $(which django-admin.py) test

after_success: coveralls

notifications:
  email: false
